import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSession, signIn, signOut } from 'next-auth/react'
import About from '../components/about'
import User from '../components/user'
import Link from 'next/link'


const Home: NextPage = () => {
  const { data: session } = useSession()
  if (session) {
    return (
      <div className={styles.container}>
        <Head>
          <title>My App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>
          <h1 className={styles.title}>
            My App
          </h1>
  
          <p className={styles.description}>
            Sign in as { session.user?.name}<br />
            <button onClick={() => signOut()}>Sign out</button>
          </p>
  
          <div className={styles.grid}>
            <div className={styles.card}><About /></div>

            <div className={styles.card}><User /></div>
  
            <Link href="/Rakuten/books" className={styles.card}>
              <h2>楽天ブックス検索 &rarr;</h2>
              <p>楽天ブックスで電子書籍（楽天Kobo）を検索</p>
            </Link>
  
            <Link href="https://nextjs.org/docs" className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </Link>
  
            <Link href="https://nextjs.org/learn" className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </Link>
  
            <Link
              href="https://github.com/vercel/next.js/tree/canary/examples"
              className={styles.card}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </Link>
  
            <Link
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </Link>
          </div>
        </main>
  
        <footer className={styles.footer}>
          <Link
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </Link>
        </footer>
      </div>
    )
  }
  return (
    <div className={styles.container}>
      <main className={styles.main}>
        Not signed in <br />
        <button onClick={() => signIn()}>Sign in</button>
      </main>
    </div>
  )
}

export default Home
